version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: todo-app:development
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  pg-dev-data:
